squid:
    build: squid/.
    environment:
        - "DISK_CACHE_SIZE=5000"
        - "MAX_CACHE_OBJECT=1000"
        # - "SQUID_DIRECTIVES_ONLY=true"
        # - "SQUID_DIRECTIVES='refresh_pattern . 0 0 1 refresh-ims'"
    net: "host"
    ## Uncomment and update /path/to/cache
    volumes:
       - /var/cache/squid:/var/cache/squid

tproxy:
    build: iptables_docker/.
    net: "host"
    privileged: true
